#!/bin/bash

cd ~/proj-skeleton
./clean.sh
echo -e "\033[38;5;148m-----------MAY CONTAIN ERROR MESSAGE-----------------------"
chmod +x pipair
make pipair
echo -e "------------------------------------------------\033[39m"
cd test2
 make
 echo -e "\033[38;5;148m-----------OUT PUT , CHECK ERROR FIRST-----------------------"
cat test2_10_80.out
echo -e "------------------------------------------------\033[39m"