#!/bin/bash

cd ~/proj-skeleton
./clean.sh
echo -e "\033[38;5;148m-----------MAY CONTAIN ERROR MESSAGE-----------------------"
make pipair
echo -e "------------------------------------------------\033[39m"
cd test2
 make
 echo -e "\033[38;5;148m-----------OUTPUT, CHECK ERRORS FIRST-----------------------"
cat test2_3_65.out
echo -e "------------------------------------------------\033[39m"